---
# tasks file for docker-registry
- name: Login Dockerhub
  docker_login:
    username: "mabroukach"
    password: "123456789"
- name: push to dockerhub
  docker_image:
    name: appfront:latest
    repository: mabroukach/cd
    push: yes
    source: local
